apiVersion: v1
kind: Namespace
metadata:
  name: skmt
annotations:
  iam.amazonaws.com/permitted: ".*"
labels:
  name: skmt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skmt
  namespace: skmt
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skmt
  namespace: skmt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skmt
subjects:
- kind: Group
  name: skmt
