apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skmt
  namespace: skmt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skmt
subjects:
- kind: Group
  name: skmt
